### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by incmve** [wranglatang/docker-bluelinky#1]
Hi thanks for making this docker.
Can you tell me what [config.validation_key](https://github.com/wranglatang/docker-bluelinky/blob/dcde99e8ebe6c3fe3a7c634544a5920b3a25e125/server.js#L16) is used for or can I just put in a random number?
And there is a [config.vin](https://github.com/wranglatang/docker-bluelinky/blob/dcde99e8ebe6c3fe3a7c634544a5920b3a25e125/server.js#L30) reference but it's not in the config file.
Thanks!

**Comment by Hacksore** [comment]
@incmve the `validation_key` was just something I added to make it more _secure_ albeit in a pretty bad way. You can put whatever you'd like for now or help make this a bit more secure :). 

As for the VIN number, I added it back as part of #2 as it was meant to be used to grab the explicit vehicle.

**Comment by incmve** [comment]
Check, thanks! 👍
